apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-basic-1777021807749
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/test-image:github-a4d9a9b6c8eca6afaffe80b2b812076e9246b372
          name: container-image
